# Generated by Django 2.1.8 on 2019-05-18 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagtailTinyPNGImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_size', models.PositiveIntegerField(default=0, help_text='Original image size before minification')),
                ('minified_size', models.PositiveIntegerField(default=0, help_text='Minified image size after minification')),
                ('date_minified', models.DateTimeField(blank=True, help_text='The date this image was minified', null=True)),
                ('wagtail_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Compressed Image',
                'verbose_name_plural': 'Compressed Images',
            },
        ),
    ]
